// Generated by scripts/make-logo.cjs. Do not edit by hand.
// Size of the wordmark image (px) and the position of its red dot, in the same pixel units.
export const LOGO = {
  "width": 1530,
  "height": 554,
  "dot": {
    "cx": 831.0403890415027,
    "cy": 70.94268319845571,
    "r": 65.5
  }
} as const;
